# Generated by Django 6.0.5 on 2026-05-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=50, unique=True)),
                ('length', models.PositiveSmallIntegerField(help_text='Letter count, set automatically on save.')),
                ('difficulty_level', models.PositiveSmallIntegerField(choices=[(1, 'Very easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very hard')], db_index=True, default=3)),
                ('definition', models.TextField(blank=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=20)),
                ('example_sentence', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['difficulty_level', 'length'], name='words_word_difficu_f25cef_idx')],
            },
        ),
    ]
