# Generated by Django 6.0.5 on 2026-05-24 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_daily', models.BooleanField(db_index=True, default=False)),
                ('daily_date', models.DateField(blank=True, db_index=True, null=True, unique=True)),
                ('max_guesses', models.PositiveSmallIntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.PositiveSmallIntegerField()),
                ('user_input', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('evaluation', models.CharField(help_text="String of G/Y/B per letter (e.g., 'GGYBB' for receive guessed as 'recent').", max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='puzzles.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField()),
                ('guesses_used', models.PositiveSmallIntegerField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['is_daily', 'daily_date'], name='puzzles_puz_is_dail_28282a_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'attempted_at'], name='puzzles_att_user_id_b72f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'puzzle'], name='puzzles_att_user_id_d5357c_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleresult',
            index=models.Index(fields=['user', 'completed_at'], name='puzzles_puz_user_id_ab3b81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puzzleresult',
            unique_together={('user', 'puzzle')},
        ),
    ]
